services:
  nginx:
    ports:
      - "${APP_HTTP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    volumes:
      - ./deploy/nginx/default-https.conf:/etc/nginx/conf.d/default.conf:ro
      - ${TLS_CERT_PATH:?Set TLS_CERT_PATH in .env.ec2}:/etc/nginx/certs/fullchain.pem:ro
      - ${TLS_KEY_PATH:?Set TLS_KEY_PATH in .env.ec2}:/etc/nginx/certs/privkey.pem:ro
